// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ChatRoom.proto
#ifndef GRPC_ChatRoom_2eproto__INCLUDED
#define GRPC_ChatRoom_2eproto__INCLUDED

#include "ChatRoom.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace Renci {

class ChatRoom final {
 public:
  static constexpr char const* service_full_name() {
    return "Renci.ChatRoom";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status sendMessage(::grpc::ClientContext* context, const ::Renci::Post& request, ::Renci::Response* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Renci::Response>> AsyncsendMessage(::grpc::ClientContext* context, const ::Renci::Post& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Renci::Response>>(AsyncsendMessageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Renci::Response>> PrepareAsyncsendMessage(::grpc::ClientContext* context, const ::Renci::Post& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Renci::Response>>(PrepareAsyncsendMessageRaw(context, request, cq));
    }
    virtual ::grpc::Status checkForMessages(::grpc::ClientContext* context, const ::Renci::Post& request, ::Renci::Response* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Renci::Response>> AsynccheckForMessages(::grpc::ClientContext* context, const ::Renci::Post& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Renci::Response>>(AsynccheckForMessagesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Renci::Response>> PrepareAsynccheckForMessages(::grpc::ClientContext* context, const ::Renci::Post& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Renci::Response>>(PrepareAsynccheckForMessagesRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void sendMessage(::grpc::ClientContext* context, const ::Renci::Post* request, ::Renci::Response* response, std::function<void(::grpc::Status)>) = 0;
      virtual void sendMessage(::grpc::ClientContext* context, const ::Renci::Post* request, ::Renci::Response* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void checkForMessages(::grpc::ClientContext* context, const ::Renci::Post* request, ::Renci::Response* response, std::function<void(::grpc::Status)>) = 0;
      virtual void checkForMessages(::grpc::ClientContext* context, const ::Renci::Post* request, ::Renci::Response* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Renci::Response>* AsyncsendMessageRaw(::grpc::ClientContext* context, const ::Renci::Post& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Renci::Response>* PrepareAsyncsendMessageRaw(::grpc::ClientContext* context, const ::Renci::Post& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Renci::Response>* AsynccheckForMessagesRaw(::grpc::ClientContext* context, const ::Renci::Post& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Renci::Response>* PrepareAsynccheckForMessagesRaw(::grpc::ClientContext* context, const ::Renci::Post& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status sendMessage(::grpc::ClientContext* context, const ::Renci::Post& request, ::Renci::Response* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Renci::Response>> AsyncsendMessage(::grpc::ClientContext* context, const ::Renci::Post& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Renci::Response>>(AsyncsendMessageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Renci::Response>> PrepareAsyncsendMessage(::grpc::ClientContext* context, const ::Renci::Post& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Renci::Response>>(PrepareAsyncsendMessageRaw(context, request, cq));
    }
    ::grpc::Status checkForMessages(::grpc::ClientContext* context, const ::Renci::Post& request, ::Renci::Response* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Renci::Response>> AsynccheckForMessages(::grpc::ClientContext* context, const ::Renci::Post& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Renci::Response>>(AsynccheckForMessagesRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Renci::Response>> PrepareAsynccheckForMessages(::grpc::ClientContext* context, const ::Renci::Post& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Renci::Response>>(PrepareAsynccheckForMessagesRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void sendMessage(::grpc::ClientContext* context, const ::Renci::Post* request, ::Renci::Response* response, std::function<void(::grpc::Status)>) override;
      void sendMessage(::grpc::ClientContext* context, const ::Renci::Post* request, ::Renci::Response* response, ::grpc::ClientUnaryReactor* reactor) override;
      void checkForMessages(::grpc::ClientContext* context, const ::Renci::Post* request, ::Renci::Response* response, std::function<void(::grpc::Status)>) override;
      void checkForMessages(::grpc::ClientContext* context, const ::Renci::Post* request, ::Renci::Response* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::Renci::Response>* AsyncsendMessageRaw(::grpc::ClientContext* context, const ::Renci::Post& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Renci::Response>* PrepareAsyncsendMessageRaw(::grpc::ClientContext* context, const ::Renci::Post& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Renci::Response>* AsynccheckForMessagesRaw(::grpc::ClientContext* context, const ::Renci::Post& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Renci::Response>* PrepareAsynccheckForMessagesRaw(::grpc::ClientContext* context, const ::Renci::Post& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_sendMessage_;
    const ::grpc::internal::RpcMethod rpcmethod_checkForMessages_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status sendMessage(::grpc::ServerContext* context, const ::Renci::Post* request, ::Renci::Response* response);
    virtual ::grpc::Status checkForMessages(::grpc::ServerContext* context, const ::Renci::Post* request, ::Renci::Response* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_sendMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_sendMessage() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_sendMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status sendMessage(::grpc::ServerContext* /*context*/, const ::Renci::Post* /*request*/, ::Renci::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestsendMessage(::grpc::ServerContext* context, ::Renci::Post* request, ::grpc::ServerAsyncResponseWriter< ::Renci::Response>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_checkForMessages : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_checkForMessages() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_checkForMessages() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status checkForMessages(::grpc::ServerContext* /*context*/, const ::Renci::Post* /*request*/, ::Renci::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestcheckForMessages(::grpc::ServerContext* context, ::Renci::Post* request, ::grpc::ServerAsyncResponseWriter< ::Renci::Response>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_sendMessage<WithAsyncMethod_checkForMessages<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_sendMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_sendMessage() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::Renci::Post, ::Renci::Response>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::Renci::Post* request, ::Renci::Response* response) { return this->sendMessage(context, request, response); }));}
    void SetMessageAllocatorFor_sendMessage(
        ::grpc::MessageAllocator< ::Renci::Post, ::Renci::Response>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::Renci::Post, ::Renci::Response>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_sendMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status sendMessage(::grpc::ServerContext* /*context*/, const ::Renci::Post* /*request*/, ::Renci::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* sendMessage(
      ::grpc::CallbackServerContext* /*context*/, const ::Renci::Post* /*request*/, ::Renci::Response* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_checkForMessages : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_checkForMessages() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::Renci::Post, ::Renci::Response>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::Renci::Post* request, ::Renci::Response* response) { return this->checkForMessages(context, request, response); }));}
    void SetMessageAllocatorFor_checkForMessages(
        ::grpc::MessageAllocator< ::Renci::Post, ::Renci::Response>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::Renci::Post, ::Renci::Response>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_checkForMessages() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status checkForMessages(::grpc::ServerContext* /*context*/, const ::Renci::Post* /*request*/, ::Renci::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* checkForMessages(
      ::grpc::CallbackServerContext* /*context*/, const ::Renci::Post* /*request*/, ::Renci::Response* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_sendMessage<WithCallbackMethod_checkForMessages<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_sendMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_sendMessage() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_sendMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status sendMessage(::grpc::ServerContext* /*context*/, const ::Renci::Post* /*request*/, ::Renci::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_checkForMessages : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_checkForMessages() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_checkForMessages() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status checkForMessages(::grpc::ServerContext* /*context*/, const ::Renci::Post* /*request*/, ::Renci::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_sendMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_sendMessage() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_sendMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status sendMessage(::grpc::ServerContext* /*context*/, const ::Renci::Post* /*request*/, ::Renci::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestsendMessage(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_checkForMessages : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_checkForMessages() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_checkForMessages() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status checkForMessages(::grpc::ServerContext* /*context*/, const ::Renci::Post* /*request*/, ::Renci::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestcheckForMessages(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_sendMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_sendMessage() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->sendMessage(context, request, response); }));
    }
    ~WithRawCallbackMethod_sendMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status sendMessage(::grpc::ServerContext* /*context*/, const ::Renci::Post* /*request*/, ::Renci::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* sendMessage(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_checkForMessages : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_checkForMessages() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->checkForMessages(context, request, response); }));
    }
    ~WithRawCallbackMethod_checkForMessages() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status checkForMessages(::grpc::ServerContext* /*context*/, const ::Renci::Post* /*request*/, ::Renci::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* checkForMessages(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_sendMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_sendMessage() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::Renci::Post, ::Renci::Response>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::Renci::Post, ::Renci::Response>* streamer) {
                       return this->StreamedsendMessage(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_sendMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status sendMessage(::grpc::ServerContext* /*context*/, const ::Renci::Post* /*request*/, ::Renci::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedsendMessage(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::Renci::Post,::Renci::Response>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_checkForMessages : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_checkForMessages() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::Renci::Post, ::Renci::Response>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::Renci::Post, ::Renci::Response>* streamer) {
                       return this->StreamedcheckForMessages(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_checkForMessages() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status checkForMessages(::grpc::ServerContext* /*context*/, const ::Renci::Post* /*request*/, ::Renci::Response* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedcheckForMessages(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::Renci::Post,::Renci::Response>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_sendMessage<WithStreamedUnaryMethod_checkForMessages<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_sendMessage<WithStreamedUnaryMethod_checkForMessages<Service > > StreamedService;
};

}  // namespace Renci


#endif  // GRPC_ChatRoom_2eproto__INCLUDED
