// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ChatRoom.proto

#include "ChatRoom.pb.h"
#include "ChatRoom.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace Renci {

static const char* ChatRoom_method_names[] = {
  "/Renci.ChatRoom/sendMessage",
  "/Renci.ChatRoom/checkForMessages",
};

std::unique_ptr< ChatRoom::Stub> ChatRoom::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ChatRoom::Stub> stub(new ChatRoom::Stub(channel, options));
  return stub;
}

ChatRoom::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_sendMessage_(ChatRoom_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_checkForMessages_(ChatRoom_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ChatRoom::Stub::sendMessage(::grpc::ClientContext* context, const ::Renci::Post& request, ::Renci::Response* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Renci::Post, ::Renci::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_sendMessage_, context, request, response);
}

void ChatRoom::Stub::async::sendMessage(::grpc::ClientContext* context, const ::Renci::Post* request, ::Renci::Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Renci::Post, ::Renci::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_sendMessage_, context, request, response, std::move(f));
}

void ChatRoom::Stub::async::sendMessage(::grpc::ClientContext* context, const ::Renci::Post* request, ::Renci::Response* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_sendMessage_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Renci::Response>* ChatRoom::Stub::PrepareAsyncsendMessageRaw(::grpc::ClientContext* context, const ::Renci::Post& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Renci::Response, ::Renci::Post, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_sendMessage_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Renci::Response>* ChatRoom::Stub::AsyncsendMessageRaw(::grpc::ClientContext* context, const ::Renci::Post& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncsendMessageRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ChatRoom::Stub::checkForMessages(::grpc::ClientContext* context, const ::Renci::Post& request, ::Renci::Response* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Renci::Post, ::Renci::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_checkForMessages_, context, request, response);
}

void ChatRoom::Stub::async::checkForMessages(::grpc::ClientContext* context, const ::Renci::Post* request, ::Renci::Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Renci::Post, ::Renci::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_checkForMessages_, context, request, response, std::move(f));
}

void ChatRoom::Stub::async::checkForMessages(::grpc::ClientContext* context, const ::Renci::Post* request, ::Renci::Response* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_checkForMessages_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Renci::Response>* ChatRoom::Stub::PrepareAsynccheckForMessagesRaw(::grpc::ClientContext* context, const ::Renci::Post& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Renci::Response, ::Renci::Post, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_checkForMessages_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Renci::Response>* ChatRoom::Stub::AsynccheckForMessagesRaw(::grpc::ClientContext* context, const ::Renci::Post& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsynccheckForMessagesRaw(context, request, cq);
  result->StartCall();
  return result;
}

ChatRoom::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatRoom_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ChatRoom::Service, ::Renci::Post, ::Renci::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ChatRoom::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Renci::Post* req,
             ::Renci::Response* resp) {
               return service->sendMessage(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ChatRoom_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ChatRoom::Service, ::Renci::Post, ::Renci::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ChatRoom::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Renci::Post* req,
             ::Renci::Response* resp) {
               return service->checkForMessages(ctx, req, resp);
             }, this)));
}

ChatRoom::Service::~Service() {
}

::grpc::Status ChatRoom::Service::sendMessage(::grpc::ServerContext* context, const ::Renci::Post* request, ::Renci::Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ChatRoom::Service::checkForMessages(::grpc::ServerContext* context, const ::Renci::Post* request, ::Renci::Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace Renci

